### ISSUE TITLE
[FE] - TODO List UI

### ISSUE THREAD

**Issue by mflavin** [mflavin/ticket-workflow#2]
## Story
- Need a UI to add, update, delete todos

```[tasklist]
### Tasks
- [ ] Need an input to save TODOs
- [ ] Need a delete to remove TODOs
- [ ] Need an update to update TODO
```

## Reference/Consideration
- Other notes
