### ISSUE TITLE
[BE] TODO List Endpoints

### ISSUE THREAD

**Issue by mflavin** [mflavin/ticket-workflow#3]
## Story
- Need to save TODO data in DB

```[tasklist]
### Tasks
- [ ] Need endpoints for frontend to query data
- [ ] Need endpoints for frontend to update data
- [ ] Need functions to validate and save data
```

## Reference/Consideration
- Other notes
